name: SendToChannelEitaa

on:
  workflow_dispatch:
  schedule:
    - cron: "30 8,14 * * *"

concurrency:
  group: configs-update
  cancel-in-progress: false

jobs:
  sendZip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create directories
        run: |
          mkdir -p Protocols
          mkdir -p Country
          mkdir -p NetworkType

      - name: Move specific files if they exist
        run: |
          [ -f category/vless.txt ] && mv category/vless.txt Protocols/
          [ -f category/ss.txt ] && mv category/ss.txt Protocols/
          [ -f category/trojan.txt ] && mv category/trojan.txt Protocols/
          [ -f category/vmess.txt ] && mv category/vmess.txt Protocols/
          [ -f category/wireguard.txt ] && mv category/wireguard.txt Protocols/
          
          [ -f category/httpupgrade.txt ] && mv category/httpupgrade.txt NetworkType/
          [ -f category/ws.txt ] && mv category/ws.txt NetworkType/
          [ -f category/xhttp.txt ] && mv category/xhttp.txt NetworkType/
          [ -f category/tcp.txt ] && mv category/tcp.txt NetworkType/
          [ -f category/grpc.txt ] && mv category/grpc.txt NetworkType/
          
          mv category/* Country/

      - name: Zip the files
        run: |
          zip -r v2rayng_free.zip Protocols Country NetworkType

      - name: Send ZIP to API
        run: |
          CAPTION=$'🆕 آخرین لیست بروزرسانی شده\n\n#v2ray #vmess #vless\n\n@v2rayng_free | مارا به دوستان خود معرفی کنید'
          
          curl -X POST "https://eitaayar.ir/api/bot${{ secrets.PERSONAL_API_KEY }}/sendFile" \
            -F "chat_id=v2rayng_free" \
            -F "file=@v2rayng_free.zip" \
            -F "caption=$CAPTION"