name: UpdateConfigs

on:
  workflow_dispatch: # اجازه اجرای دستی
  schedule:
    - cron: "30 */2 * * *"

jobs:
  UpdateConfigs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Remove And Replace New Configs
        run: |
          mkdir -p category
          rm -f category/*
          > BadChannels.txt

      - name: Run index.ts
        run: bun index.ts

      - name: Upload category artifact
        uses: actions/upload-artifact@v4
        with:
          name: category
          path: category/
          retention-days: 7

      - name: Commit BadChannels
        run: |
          git config --local user.name "Robot-1"
          git config --local user.email "Robot@example.com"
          git add BadChannels.txt
          if git diff --staged --quiet; then
            echo "No BadChannels changes to commit"
          else
            git commit -m "Update BadChannels"
            git push
          fi
