name: UpdateConfigs

on:
  workflow_dispatch: # اجازه اجرای دستی
  schedule:
    - cron: "30 */2 * * *"

jobs:
  UpdateConfigs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Install dependencies
      - name: Install Dependencies
        run: bun install

      - name: Remove And Replace New Configs
        run: |
          mkdir -p category
          rm -f category/*
          > BadChannels.txt

      # Run the index.ts file
      - name: Run index.ts
        run: bun index.ts

      # Commit changes
      - name: Commit Changes To UpdateConfigs
        run: |
          git config --local user.name "Robot-1"
          git config --local user.email "Robot@example.com"
          git add -A --ignore-removal category/* BadChannels.txt
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "UpdateConfigs"
            git push
          fi
